version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'task_manager'
      MYSQL_USER: 'task_manager'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/task_manager
      SPRING_DATASOURCE_USERNAME: task_manager
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

volumes:
  db-data:
