version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: task_management_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ryuqerb524543GGRWEHR
      MYSQL_DATABASE: task_management
      MYSQL_USER: root
      MYSQL_PASSWORD: ryuqerb524543GGRWEHR
    ports:
      - "3306:3306"
    networks:
      - task_management_network

  task-management-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_management_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ryuqerb524543GGRWEHR
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - task_management_network

networks:
  task_management_network:
    driver: bridge
